name: ci-python

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.12"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
